---
- name: Build OpenWrt
  hosts: localhost
  gather_facts: no
  vars:
    openwrt_version: 19.07.10
    openwrt_target: ar71xx
    openwrt_subtarget: generic
    openwrt_device_list: 
      - ubnt-lbe-m5:
      - ubnt-loco-m-xw:
      - ubnt-nano-m-xw:
      - ubnt-nano-m:
  roles: libremesh.openwrt_buildroot

