---
- name: Build LibreMesh {{libremesh_version}}
  hosts: localhost
  gather_facts: no
  vars:
    libremesh_version: master
    openwrt_version: 22.03.5
    libremesh_community: new-community
    libremesh_community_recipe: libremesh.defaults
  roles: 
    - libremesh.libremesh.openwrt_imagebuilder_docker
    # - libremesh.libremesh.openwrt_imagebuilder
    # - libremesh.libremesh.openwrt_buildroot
