---
- name: Build LibreMesh {{libremesh_version}}
  hosts: localhost
  gather_facts: no
  vars:
    libremesh_community: new-community
    libremesh_community_variables_file: stable
    libremesh_version: 2023.1
    openwrt_version: 22.03.5
    openwrt_targets:
      - openwrt_target: ath79
        openwrt_subtarget: generic
        openwrt_devices: 
        - name: ubnt_nanostation-m-xw    
  roles: 
    - libremesh.libremesh.openwrt_imagebuilder_docker
    # - libremesh.libremesh.openwrt_imagebuilder
    # - libremesh.libremesh.openwrt_buildroot