---
- name: Build LibreMesh {{ libremesh_version }}
  hosts: localhost
  gather_facts: no
  vars:
    libremesh_version: master
    openwrt_version: 22.03.5
    libremesh_community: libremesh
    libremesh_community_recipe: stable
    openwrt_targets:
      - openwrt_target: ath79
        openwrt_subtarget: generic
        openwrt_devices: 
          - name: ubnt_nanostation-m-xw    
  roles: 
    - libremesh.libremesh.openwrt_imagebuilder_docker       

